// Identité & session — challenges jouables.
//
// Un seul fil : tout ce qui permet de devenir quelqu'un d'autre. L'inscription
// (M7), les courses et les protocoles de jetons (M9), l'aléa des secrets (M13),
// la fédération OAuth/OIDC/SAML (M14) et l'anti-abus (M15). Ils sont regroupés
// ici parce qu'ils partagent leur code — server/routes/auth.ts, server/lib/ et
// les deux routeurs de fédération — et non parce qu'ils partagent un module.
//
// Le défaut de chacun est commenté sur place, `// VULNÉRABLE (id) :`, avec le
// correctif attendu. Le corrigé complet est dans solutions/server/.

import type { ExerciseDef } from '../exercises.ts';

export const identity: ExerciseDef[] = [
  // ─── m02 · Vulnérabilités web, écosystème JS ───────────────────────────────
  {
    id: 'regex-unanchored',
    module: 'm02',
    title: 'Expression de validation non ancrée',
    status: 'live',
    kind: 'exploit',
    level: 1,
    csslp: ['D5'],
    cwe: 'CWE-625',
    brief:
      'La liste blanche de domaines d’inscription teste une expression sans ancres : elle accepte tout ce qui *contient* le domaine.',
    goal: 'Créer un compte avec une adresse que la liste blanche devait refuser, et hériter de l’appartenance au tenant.',
    file: 'server/routes/auth.ts',
    lessons: ['m02/l01', 'm10/l02'],
    hints: [
      'POST /api/auth/register n’accepte que trois domaines. Regarde comment il les reconnaît.',
      'Sans `^` ni `$`, une expression décrit une sous-chaîne. Où peux-tu placer `acme.example` pour qu’il ne soit plus le domaine de l’adresse ?',
      'Inscris `pirate@acme.example.attaquant.test` : la sous-chaîne satisfait la liste, et le compte est rattaché au tenant acme.',
    ],
    fix: 'Une expression de validation s’ancre (`^…$`), sinon elle décrit une sous-chaîne et non la valeur. Plus sûr encore : ne pas valider un domaine par expression, mais comparer la partie droite après un découpage explicite.',
    k: [10],
  },
  {
    id: 'unicode-normalization',
    module: 'm02',
    title: 'Normalisation après le contrôle d’unicité',
    status: 'live',
    kind: 'exploit',
    level: 2,
    csslp: ['D5'],
    cwe: 'CWE-178',
    brief:
      'L’adresse est vérifiée comme unique, puis normalisée et mise en minuscules — ce qui la fait collisionner avec un compte existant.',
    goal: 'Créer un second compte qui résout vers l’adresse de l’administrateur, et recevoir un message qui lui était destiné.',
    file: 'server/routes/auth.ts',
    lessons: ['m02/l02', 'm03/l07'],
    hints: [
      'L’inscription contrôle l’unicité sur ce que tu envoies, et range autre chose. Compare les deux formes dans le code.',
      'NFKC replie beaucoup de caractères sur leur équivalent ASCII. Le contrôle de domaine, lui, travaille déjà sur la forme canonique — pas le contrôle d’unicité.',
      'Inscris `admin@ｎｏｖａｆａｃｔ.example` (domaine en caractères pleine chasse, U+FF4E…). L’adresse est unique à l’entrée, se range sous `admin@novafact.example`, et le courrier de bienvenue part à l’administrateur : regarde /api/lab/mails.',
    ],
    fix: 'Normaliser **avant** de comparer, une seule fois, et stocker la forme normalisée. Les pièges classiques : le İ turc sous `toLowerCase`, les équivalences NFKC, les caractères invisibles. Deux couches qui normalisent différemment, c’est une faille d’authentification.',
    k: [8],
  },
  {
    id: 'try-catch-fail-open',
    module: 'm02',
    title: 'Le catch qui échoue ouvert',
    status: 'live',
    kind: 'exploit',
    level: 2,
    csslp: ['D5'],
    cwe: 'CWE-636',
    brief:
      'L’appel au moteur d’autorisation est enveloppé dans un `catch` vide, et l’exécution continue comme si l’accès était accordé.',
    goal: 'Provoquer l’exception par une entrée malformée, puis lire une ressource d’un autre tenant.',
    file: 'server/lib/auth.ts',
    lessons: ['m02/l04', 'm12/l05'],
    hints: [
      'GET /api/auth/directory sert l’annuaire d’un tenant. Avec `?tenant=globex`, il refuse. Lis ce que fait `requireDirectoryAccess`.',
      'Le moteur suppose que sa ressource est une chaîne. L’analyseur de query string d’Express sait fabriquer autre chose.',
      'Appelle `GET /api/auth/directory?tenant[]=globex` avec ton jeton : `req.query.tenant` devient un tableau, `can()` lève, le `catch` avale, et l’annuaire de Globex part dans la réponse.',
    ],
    fix: 'Un contrôle qui ne sait pas répondre doit refuser : l’échec sûr est le comportement par défaut, pas une option. Et un `catch` vide dans un chemin d’autorisation est un motif que Semgrep trouve en une règle.',
    k: [13],
  },
  {
    id: 'input-truncation',
    module: 'm02',
    title: 'Troncature après validation',
    status: 'live',
    kind: 'exploit',
    level: 2,
    csslp: ['D5'],
    cwe: 'CWE-1284',
    brief:
      'L’adresse est validée, puis tronquée à la longueur de la colonne — ce qui change le domaine et donc le tenant de rattachement.',
    goal: 'S’inscrire et se retrouver rattaché au tenant d’un autre, avec ses droits.',
    file: 'server/routes/auth.ts',
    lessons: ['m02/l04', 'm07/l01'],
    hints: [
      'POST /api/auth/register/partner accepte les sous-domaines des clients. Cherche ce qui arrive à l’adresse APRÈS le contrôle.',
      'La colonne fait 32 caractères. Compte : si la coupure tombe pile après un autre domaine client, c’est lui que la base contiendra.',
      'Inscris `aaaaaaaaaaaaaaaaa@globex.example.acme.example` (17 « a »). Le domaine validé est un sous-domaine d’acme ; les 32 premiers caractères donnent `…@globex.example`, et le compte naît chez Globex.',
    ],
    fix: 'Toute transformation postérieure à la validation invalide la validation. Longueurs contraintes par le schéma d’entrée, jamais par la base, et le rejet plutôt que la correction silencieuse.',
    k: [10],
  },
  {
    id: 'timing-attack',
    module: 'm02',
    title: 'Comparaison de jeton à temps variable',
    status: 'live',
    kind: 'exploit',
    level: 2,
    csslp: ['D5'],
    cwe: 'CWE-208',
    brief:
      'Le jeton de réinitialisation est comparé avec `===`, qui s’arrête au premier octet différent.',
    goal: 'Retrouver un jeton de réinitialisation octet par octet, en mesurant le temps de réponse.',
    file: 'server/routes/auth.ts',
    lessons: ['m02/l04', 'm08/l07'],
    hints: [
      'POST /api/auth/reset attend `{ email, token, password }`. Le jeton fait 8 caractères hexadécimaux. Chronomètre la réponse.',
      'La comparaison s’arrête au premier écart, et chaque caractère validé coûte un aller-retour : plus le préfixe est bon, plus la réponse est lente.',
      'Demande un jeton pour `admin@novafact.example`, puis, position par position, essaie les 16 chiffres hexadécimaux (le reste rempli de « 0 ») et garde le plus lent — médiane sur 3 mesures. Au dernier caractère, ce n’est plus le chronomètre qui trahit mais le 200.',
    ],
    fix: '`crypto.timingSafeEqual` sur des tampons de longueur fixe, ou comparaison d’empreintes plutôt que de secrets. Et un jeton assez court-vécu pour que la mesure n’ait pas le temps d’aboutir.',
    k: [8],
  },
  {
    id: 'open-redirect',
    module: 'm04',
    title: 'Redirection ouverte après connexion',
    status: 'live',
    kind: 'exploit',
    level: 1,
    csslp: ['D5'],
    cwe: 'CWE-601',
    brief: 'Le paramètre de retour est suivi tel quel après une connexion réussie.',
    goal: 'Faire rediriger un utilisateur connecté vers un domaine que tu contrôles.',
    file: 'server/routes/auth.ts',
    lessons: ['m04/l02', 'm09/l06'],
    hints: [
      'La connexion accepte un champ de plus que les deux que tu connais.',
      'Ce champ finit dans l’en-tête `Location` d’une réponse 303, sans que personne ne regarde où il pointe.',
      'POST /api/auth/login avec `{ email, password, next: "https://attaquant.test/vol" }`, puis lis l’en-tête Location (avec `curl -i`, ou `redirect: "manual"` côté fetch).',
    ],
    fix: 'Chemins relatifs seulement, ou liste blanche de destinations. Une redirection ouverte est rarement isolée : elle sert de tremplin au vol de code OAuth et au contournement de filtres SSRF.',
  },

  // ─── m03 · Web avancé ──────────────────────────────────────────────────────
  {
    id: 'race-partial-construction',
    module: 'm03',
    title: 'Course à la construction du compte',
    status: 'live',
    kind: 'exploit',
    level: 3,
    csslp: ['D5'],
    cwe: 'CWE-362',
    brief:
      'Le compte est inséré, puis son empreinte de mot de passe écrite dans un second temps. Pendant la fenêtre, le champ est vide et la comparaison le laisse passer.',
    goal: 'Se connecter à un compte pendant sa création, sans en connaître le mot de passe.',
    file: 'server/routes/auth.ts',
    lessons: ['m03/l01', 'm09/l01'],
    hints: [
      'L’inscription fait deux écritures, séparées par un `await`. Demande-toi à quoi ressemble l’enregistrement entre les deux.',
      'Pendant ces 40 millisecondes, le mot de passe stocké est la chaîne vide — et la connexion compare sans jamais refuser une valeur absente.',
      'Lance POST /api/auth/register pour `course@acme.example` SANS attendre la réponse, et martèle en parallèle POST /api/auth/login avec `{ email: "course@acme.example", password: "" }` : l’un des essais ouvre une session.',
    ],
    fix: 'Un enregistrement à moitié construit est visible : créer en une transaction, ou insérer d’abord dans un état inutilisable. Et une comparaison de mot de passe refuse une valeur absente au lieu de l’accepter. *Partial construction*, Smashing the state machine.',
  },
  {
    id: 'reset-token-collision',
    module: 'm03',
    title: 'Jetons de réinitialisation collidants',
    status: 'live',
    kind: 'exploit',
    level: 2,
    csslp: ['D5'],
    cwe: 'CWE-330',
    brief:
      'Le jeton est dérivé de l’horloge et d’un générateur non cryptographique : deux demandes dans la même milliseconde produisent le même jeton.',
    goal: 'Obtenir un jeton valide pour le compte d’un autre utilisateur en déclenchant deux réinitialisations simultanées.',
    file: 'server/routes/auth.ts',
    lessons: ['m03/l01', 'm08/l07'],
    hints: [
      'Regarde `mintResetToken` : le générateur n’avance pas à chaque appel.',
      'Il n’avance qu’une fois par milliseconde. Deux demandes traitées dans la même milliseconde repartent donc avec la même valeur.',
      'Envoie en parallèle POST /api/auth/forgot pour `dev@acme.example` et pour `admin@novafact.example` (un `Promise.all`, répété quelques fois), puis lis TON courrier dans /api/lab/mails : le jeton qu’il contient ouvre aussi le compte admin.',
    ],
    fix: 'Un jeton vient d’un générateur cryptographique, et rien d’autre. L’unicité se garantit par une contrainte en base, pas par l’espoir que deux appels ne tombent pas au même instant.',
    k: [5],
  },
  {
    id: 'email-parsing-differential',
    module: 'm03',
    title: 'Différentiel d’analyse d’adresse',
    status: 'live',
    kind: 'exploit',
    level: 3,
    csslp: ['D5'],
    cwe: 'CWE-436',
    brief:
      'L’appartenance au tenant est déduite par un découpage naïf sur l’arobase, alors que la couche d’envoi lit un autre domaine dans la même adresse.',
    goal: 'Faire reconnaître comme membre du tenant Novafact une adresse dont le courrier part ailleurs.',
    file: 'server/routes/auth.ts',
    lessons: ['m03/l07', 'm09/l06'],
    hints: [
      'Le domaine `novafact.example` donne le rôle comptable, mais l’inscription libre le refuse. Regarde AVEC QUEL découpage elle le refuse.',
      'Le garde-fou lit le domaine qui suit le premier arobase ; l’appartenance, elle, vient de celui de la fin. Rien n’interdit d’en mettre deux.',
      'Inscris `pirate@evil.test@novafact.example` : le garde-fou voit `evil.test`, le tenant est lu sur `novafact.example`, et le courrier de bienvenue part chez `pirate@evil.test` (visible dans /api/lab/mails).',
    ],
    fix: 'Deux composants qui analysent la même chaîne différemment forment une faille d’autorisation. Une seule bibliothèque d’analyse, une forme canonique stockée, et l’appartenance au tenant décidée par une invitation — pas devinée depuis un domaine. *Splitting the email atom*, 2024.',
  },
  {
    id: 'cookie-deserialization',
    module: 'm03',
    title: 'Cookie de préférences désérialisé',
    status: 'live',
    kind: 'exploit',
    level: 3,
    csslp: ['D5'],
    cwe: 'CWE-502',
    brief:
      'Les préférences sont un objet sérialisé, signé avec une clé faible, puis désérialisé sans liste de types autorisés.',
    goal: 'Forger un cookie qui, à la désérialisation, élève le rôle de son porteur.',
    file: 'server/lib/auth.ts',
    lessons: ['m03/l09', 'm08/l07'],
    hints: [
      'POST /api/auth/prefs pose un cookie `novafact_prefs`. Décode-le : il commence par du base64url et finit par une signature.',
      'Le champ `$t` du document désigne le constructeur à appeler, et le désérialiseur en connaît deux. Le second n’a rien à faire dans un cookie.',
      'Forge `{"$t":"Session","email":"dev@acme.example","role":"admin","tenantId":"acme"}` en base64url, signe-le en HMAC-SHA256 avec la clé `nova1` (22 premiers caractères du digest base64url), et envoie `Cookie: novafact_prefs=<corps>.<mac>`.',
    ],
    fix: 'Un format qui reconstruit des objets typés ne se met pas dans un cookie. JSON avec schéma strict, état côté serveur, et signature avec une clé issue d’un générateur cryptographique. La signature ne sauve pas un format dangereux — elle retarde seulement.',
    k: [8],
  },
  {
    id: 'jwt-kid-traversal',
    module: 'm03',
    title: 'JWT : kid en traversée de chemin',
    status: 'live',
    kind: 'exploit',
    level: 3,
    csslp: ['D1', 'D5'],
    cwe: 'CWE-22',
    brief: 'L’en-tête `kid` du jeton désigne le fichier de clé à charger, sans normalisation du chemin.',
    goal: 'Forger un jeton accepté comme administrateur, en pointant l’identifiant de clé vers un fichier au contenu prévisible.',
    file: 'server/lib/jwt.ts',
    lessons: ['m03/l10', 'm09/l05'],
    hints: [
      'Les jetons du lab portent un `kid`. Regarde `keyFor()` : que se passe-t-il quand il est inconnu du trousseau ?',
      'Il devient un chemin de fichier, sans normalisation. Il te faut donc un fichier dont tu connais les octets exacts.',
      'Signe un jeton HS256 avec une clé VIDE et l’en-tête `{"alg":"HS256","kid":"../../../../../../../../../../dev/null"}`, charge utile `{"sub":"admin@novafact.example","role":"admin","tenantId":"acme"}`, puis présente-le en Bearer.',
    ],
    fix: '`kid` est un identifiant opaque : il sert à chercher dans un trousseau, jamais à construire un chemin ni une requête. Les clés viennent d’un JWKS connu d’avance.',
  },
  {
    id: 'jwt-jku-jwk',
    module: 'm03',
    title: 'JWT : jku et jwk honorés',
    status: 'live',
    kind: 'exploit',
    level: 3,
    csslp: ['D1', 'D5'],
    cwe: 'CWE-347',
    brief:
      'Le vérificateur récupère la clé publique à l’URL indiquée dans le jeton, ou l’accepte directement en en-tête.',
    goal: 'Forger un jeton signé avec ta propre paire de clés et être accepté comme un autre utilisateur.',
    file: 'server/lib/jwt.ts',
    lessons: ['m03/l10', 'm09/l05'],
    hints: [
      '`readToken` ne gère pas que HS256. Regarde ce qu’il fait des en-têtes `jwk` et `jku`.',
      'La clé publique de vérification est lue DANS le jeton : rien ne t’empêche d’y mettre la tienne.',
      'Génère une paire RSA 2048, exporte la clé publique au format JWK, mets-la dans l’en-tête `{"alg":"RS256","jwk":{…}}`, signe `header.payload` en RSA-SHA256 avec ta clé privée, et présente le jeton en Bearer.',
    ],
    fix: 'Le jeton ne choisit jamais sa clé de vérification : le serveur connaît son JWKS, son émetteur et ses algorithmes. RFC 8725, qui dit exactement cela.',
  },
  {
    id: 'jwt-no-audience',
    module: 'm03',
    title: 'Jeton valable d’un tenant à l’autre',
    status: 'live',
    kind: 'exploit',
    level: 2,
    csslp: ['D1', 'D5'],
    cwe: 'CWE-863',
    brief:
      'Tous les tenants partagent la clé de signature, et le jeton ne porte aucune revendication d’audience ni d’émetteur.',
    goal: 'Présenter sur l’API d’un tenant un jeton émis pour un autre, et y agir.',
    file: 'server/lib/jwt.ts',
    lessons: ['m03/l10', 'm09/l05'],
    hints: [
      'Chaque client a son déploiement : GET /api/auth/deployment/:tenantId/whoami. Décode ton jeton et cherche `aud` ou `iss`.',
      'Ils n’y sont pas, et la clé de signature est la même partout : rien ne dit à quel déploiement ce jeton était destiné.',
      'Connecte-toi avec `dev@acme.example` (jeton émis pour acme), puis appelle GET /api/auth/deployment/globex/whoami avec ce même jeton.',
    ],
    fix: 'Vérifier `iss` et `aud` fait partie de la vérification, au même titre que la signature : une signature valide prouve l’origine, pas la destination. Et une clé par périmètre quand les périmètres sont distincts.',
  },
  {
    id: 'session-not-revocable',
    module: 'm03',
    title: 'Session qu’on ne peut pas révoquer',
    status: 'live',
    kind: 'exploit',
    level: 2,
    csslp: ['D1', 'D5'],
    cwe: 'CWE-613',
    brief:
      'La déconnexion efface le cookie côté client ; le jeton reste valide, et son expiration n’est pas vérifiée côté serveur.',
    goal: 'Réutiliser un jeton après déconnexion, et au-delà de sa date d’expiration.',
    file: 'server/lib/jwt.ts',
    lessons: ['m03/l10', 'm09/l04'],
    hints: [
      'POST /api/auth/logout répond `ok`. Cherche ce qu’il change côté serveur — et ce que `readToken` consulte.',
      'Il faut les deux moitiés : un jeton réutilisé après déconnexion, ET un jeton dont `exp` est dépassé.',
      'Connecte-toi, appelle /api/auth/logout avec ton jeton, puis rappelle /api/auth/deployment/acme/whoami avec le même jeton. Envoie ensuite un jeton `alg:none` dont `exp` est dans le passé.',
    ],
    fix: 'Un jeton sans état ne se révoque pas : durée de vie courte, rotation du jeton de rafraîchissement, et liste de révocation pour les cas qui comptent (changement de mot de passe, compromission). Se déconnecter doit avoir un effet côté serveur.',
  },

  // ─── m08 · Conception sécurisée & architecture ─────────────────────────────
  {
    id: 'weak-random',
    module: 'm08',
    title: 'Jeton tiré de Math.random',
    status: 'live',
    kind: 'exploit',
    level: 2,
    csslp: ['D1', 'D5'],
    cwe: 'CWE-338',
    brief:
      'Le jeton de réinitialisation vient de `Math.random()`. Le générateur de V8 n’est pas cryptographique et son état se reconstruit.',
    goal: 'Prédire le prochain jeton de réinitialisation après en avoir observé quelques-uns.',
    file: 'server/routes/auth.ts',
    lessons: ['m08/l07', 'm02/l02'],
    hints: [
      'Le jeton fait 8 caractères hexadécimaux — soit exactement 32 bits. Lis `mintResetToken`.',
      'La sortie EST l’état du générateur : une seule valeur observée suffit à calculer toutes les suivantes (xorshift32 : `x ^= x<<13; x >>>= 0; x ^= x>>>17; x ^= x<<5; x >>>= 0`).',
      'Demande un jeton pour TON compte, lis-le dans /api/lab/mails, calcule le suivant, soumets-le d’abord à POST /api/auth/reset pour `admin@novafact.example` (il est refusé : il n’existe pas encore), puis déclenche /api/auth/forgot pour l’admin — le serveur constate alors qu’il avait été deviné avant d’exister.',
    ],
    fix: '`crypto.randomUUID()` ou `crypto.randomBytes` pour tout ce qui doit être imprévisible — jamais `Math.random`, dont ce n’est pas le contrat. Envelopper la génération de secrets dans une fonction maison, pour que le mauvais choix ne soit plus à portée de main.',
    k: [5],
  },

  // ─── m09 · OAuth 2.x / OIDC / SAML ─────────────────────────────────────────
  {
    id: 'oauth-redirect',
    module: 'm09',
    title: 'redirect_uri validée par préfixe',
    status: 'live',
    kind: 'exploit',
    level: 2,
    csslp: ['D1', 'D5'],
    cwe: 'CWE-601',
    brief: 'Le serveur d’autorisation du lab accepte toute `redirect_uri` qui commence par l’URL enregistrée.',
    goal: 'Détourner un code d’autorisation vers une destination que tu contrôles.',
    file: 'server/routes/oauth.ts',
    lessons: ['m09/l03', 'm09/l06'],
    hints: [
      'Le client `novafact-web` est enregistré avec `http://127.0.0.1:5199/oauth/callback`. Regarde comment /api/oauth/authorize compare.',
      '`startsWith` n’est pas une égalité : tout ce que tu ajoutes À LA SUITE de l’URI enregistrée passe le contrôle.',
      'Crée une identité chez le fournisseur (POST /api/oauth/idp/register), puis appelle GET /api/oauth/authorize avec `redirect_uri=http://127.0.0.1:5199/oauth/callback.attaquant.test/vol` : le code part dans le Location.',
    ],
    fix: 'Comparaison exacte de la `redirect_uri`, chaîne par chaîne — jamais par préfixe, jamais avec des jokers. PKCE limite les dégâts mais ne remplace pas ce contrôle. RFC 9700.',
  },
  {
    id: 'oauth-state',
    module: 'm09',
    title: 'Connexion fédérée sans state',
    status: 'live',
    kind: 'exploit',
    level: 2,
    csslp: ['D1', 'D5'],
    cwe: 'CWE-352',
    brief: 'Le flux Authorization Code n’émet ni ne vérifie de `state`.',
    goal: 'Lier le compte fédéré de l’attaquant à la session d’un autre utilisateur (login CSRF).',
    file: 'server/routes/oauth.ts',
    lessons: ['m09/l03', 'm09/l06'],
    hints: [
      'GET /api/oauth/start renvoie `state: null`, et /api/oauth/callback ne compare rien au retour.',
      'Rien ne lie donc un code à la session qui l’a demandé : un code obtenu dans TA session sera consommé dans n’importe quelle autre.',
      'Avec ton jeton, obtiens un code (idp/register puis /authorize avec la redirect_uri enregistrée), puis fais appeler GET /api/oauth/callback?code=… avec le jeton de `compta@globex.example` : son compte est rattaché à TON identité fédérée.',
    ],
    fix: '`state` aléatoire lié à la session et vérifié au retour, `nonce` pour l’ID token. Ce ne sont pas des options du flux : sans eux, le flux ne prouve rien sur l’origine de la requête.',
  },
  {
    id: 'oauth-email-unverified',
    module: 'm09',
    title: 'nOAuth : e-mail non vérifié',
    status: 'live',
    kind: 'exploit',
    level: 2,
    csslp: ['D1', 'D5'],
    cwe: 'CWE-287',
    brief:
      'Le rapprochement de comptes se fait sur le claim `email` du fournisseur, sans regarder `email_verified`.',
    goal: 'Prendre le contrôle d’un compte existant en déclarant son adresse chez un fournisseur complaisant.',
    file: 'server/routes/oauth.ts',
    lessons: ['m09/l06', 'm09/l01'],
    hints: [
      'POST /api/oauth/idp/register te laisse déclarer l’adresse de ton choix chez le fournisseur. Ce n’est pas le défaut — c’est la réalité du modèle fédéré.',
      'Le défaut est dans /api/oauth/callback, qui retrouve le compte local sur le claim `email` sans jamais regarder `email_verified`.',
      'Enregistre `{ "sub": "pirate", "email": "admin@novafact.example" }` (sans `email_verified`), passe par /api/oauth/authorize avec la redirect_uri enregistrée, puis appelle /api/oauth/callback?code=… SANS jeton : la réponse contient une session administrateur.',
    ],
    fix: 'Ne jamais rapprocher deux comptes sur un identifiant que l’utilisateur choisit. Clé de rapprochement = `iss` + `sub`, et `email_verified` exigé avant toute liaison — avec confirmation explicite côté utilisateur.',
  },
  {
    id: 'saml-wrapping',
    module: 'm09',
    title: 'SAML : envelopper la signature',
    status: 'live',
    kind: 'exploit',
    level: 3,
    csslp: ['D1', 'D4'],
    cwe: 'CWE-347',
    brief:
      'Le SSO entreprise accepte une assertion SAML dont la signature est valide — mais le traitement lit un autre nœud que celui qui a été signé.',
    goal: 'Se connecter en tant qu’un autre utilisateur avec une assertion dont la signature reste parfaitement valide.',
    file: 'server/routes/saml.ts',
    lessons: ['m09/l08', 'm03/l07'],
    hints: [
      'POST /api/saml/idp/assert te signe une assertion, mais seulement pour une adresse `@acme.example`. Pars de celle-là, sans y toucher.',
      'La vérification suit `Reference URI` et ne valide que ce nœud-là ; l’extraction du sujet, elle, reprend le premier `<saml:NameID>` du DOCUMENT.',
      'Insère, juste après `<samlp:Response …>`, une seconde assertion NON signée `<saml:Assertion ID="_evil">…<saml:NameID>admin@novafact.example</saml:NameID>…</saml:Assertion>`, laisse l’originale intacte, et poste le tout en base64 dans `SAMLResponse` sur /api/saml/acs.',
    ],
    fix: 'Vérifier la signature ne suffit pas : il faut vérifier que ce qu’on lit est **ce qui a été signé**, et refuser les documents à plusieurs assertions. Bibliothèque à jour, schéma strict, et certificats gérés. C’est la famille de SAMLStorm et de *The Fragile Lock*.',
  },

  // ─── m10 · Anti-abus, ATO & fraude ────────────────────────────────────────
  {
    id: 'user-enumeration',
    module: 'm10',
    title: 'Énumération de comptes',
    status: 'live',
    kind: 'exploit',
    level: 1,
    csslp: ['D5'],
    cwe: 'CWE-204',
    brief:
      'L’inscription, la connexion et la réinitialisation répondent différemment selon que le compte existe.',
    goal: 'Déterminer, parmi une liste de mille adresses, lesquelles ont un compte.',
    file: 'server/routes/auth.ts',
    lessons: ['m10/l02', 'm09/l01'],
    hints: [
      'Compare la réponse de POST /api/auth/register pour une adresse libre et pour une adresse déjà prise.',
      '409 « cette adresse est déjà utilisée » contre 201 : c’est un oracle d’existence, et il ne coûte rien à interroger.',
      'Passe une liste d’adresses des domaines autorisés dans /api/auth/register et retiens les 409 : confirme-en trois (`dev@acme.example`, `compta@globex.example`, `admin@novafact.example`).',
    ],
    fix: 'Réponses et temps de réponse identiques dans les trois parcours, message neutre, et la différence communiquée par e-mail plutôt que par la réponse HTTP. L’énumération est rarement critique seule : elle alimente le credential stuffing.',
  },
  {
    id: 'xff-spoof',
    module: 'm10',
    title: 'Limitation contournée par X-Forwarded-For',
    status: 'live',
    kind: 'exploit',
    level: 2,
    csslp: ['D5', 'D7'],
    cwe: 'CWE-290',
    brief:
      'La limitation de débit prend la première valeur de `X-Forwarded-For`, que le client contrôle entièrement.',
    goal: 'Mener une rafale de connexions sans jamais être limité.',
    file: 'server/routes/auth.ts',
    lessons: ['m10/l03', 'm03/l02'],
    hints: [
      'La connexion finit par répondre 429 : 100 requêtes par minute et par adresse. Trouve d’où vient cette « adresse ».',
      '`rateKey()` lit la première valeur de `X-Forwarded-For` — un en-tête que tu écris toi-même.',
      'Envoie 130 POST /api/auth/login avec `X-Forwarded-For: 203.0.113.<n>, 10.0.0.1`, en changeant `n` à chaque requête : aucune n’est refusée.',
    ],
    fix: 'Derrière CloudFront, la vraie IP est à une position connue de la chaîne : `trust proxy` réglé au nombre exact de proxys, ou lecture de l’en-tête signé du CDN. Et limiter aussi par compte, qui ne se falsifie pas.',
  },
];
