// M14 · Pipeline, supply chain & fournisseurs — challenges jouables.
//
// Challenges « fix » : le défaut vit dans le dépôt fixture `novafact/`, pas
// dans une requête. On l'audite, on corrige le fichier, et on relance l'audit
// — depuis la page du challenge ou par POST /api/lab/audit.
//
// Les vérifications correspondantes sont dans server/audit/m14.ts.

import type { ExerciseDef } from '../exercises.ts';

export const m14: ExerciseDef[] = [
  {
    id: 'gha-permissions', module: 'm14', title: 'Permissions de workflow trop larges',
    status: 'live', kind: 'fix', level: 1, csslp: ['D7', 'D8'], cwe: 'CWE-732',
    brief: 'Les workflows tournent avec le jeton par défaut, en écriture sur tout le dépôt.',
    goal: 'Déclarer les permissions au minimum nécessaire dans chaque workflow, sans laisser de write-all.',
    file: 'novafact/.github/workflows/ci.yml',
    lessons: ['m14/l02', 'm14/l01'],
    hints: [
      'Regarde quels workflows ne déclarent aucun bloc `permissions`.',
      'Le minimum se pose en tête de workflow, puis s’élève job par job si besoin.',
      'Ajoute un bloc `permissions:` avec `contents: read` au niveau de chaque workflow.',
    ],
    fix: 'Le minimum au niveau du workflow, puis le strict nécessaire par job. Une permission accordée « au cas où » est une permission qu’un script compromis utilisera. CICD-SEC-5, OpenSSF Scorecard `Token-Permissions`.',
  },
  {
    id: 'gha-injection', module: 'm14', title: 'Injection de template dans un run',
    status: 'live', kind: 'fix', level: 2, csslp: ['D7', 'D8'], cwe: 'CWE-94',
    brief: 'Un workflow interpole le titre d’une issue directement dans un bloc `run`. Ce titre devient une commande shell.',
    goal: 'Faire passer la donnée non fiable par l’environnement, et la citer dans le script.',
    file: 'novafact/.github/workflows/triage.yml',
    lessons: ['m14/l02', 'm14/l04'],
    hints: [
      'L’interpolation a lieu AVANT que le shell ne voie la ligne.',
      'Ce qui vient de `github.event.*` n’a rien à faire dans un `run:`.',
      'Déclare la valeur dans un bloc `env:` du step, puis utilise `"$MA_VAR"` dans le script.',
    ],
    fix: 'Les entrées non fiables passent par l’environnement et sont citées, jamais interpolées dans le script. `zizmor` (règle `template-injection`) et `actionlint` attrapent le motif. Cas Ultralytics, déc. 2024.',
  },
  {
    id: 'gha-pwn-request', module: 'm14', title: 'Pwn request sur pull_request_target',
    status: 'live', kind: 'fix', level: 2, csslp: ['D7', 'D8'], cwe: 'CWE-269',
    brief: 'Un workflow `pull_request_target` fait un checkout du commit de la pull request puis lance le build — donc exécute du code de fork avec les secrets du dépôt.',
    goal: 'Faire en sorte qu’aucun code non revu ne s’exécute dans un contexte qui a les secrets.',
    file: 'novafact/.github/workflows/pr-check.yml',
    lessons: ['m14/l02', 'm14/l07'],
    hints: [
      '`pull_request_target` s’exécute dans le contexte de la base, avec ses secrets.',
      'Le checkout du commit de la PR ramène le code de l’attaquant dans ce contexte.',
      'Bascule sur `pull_request`, ou retire le checkout du head et l’étape qui exécute.',
    ],
    fix: 'Séparer le job qui construit (déclenché par `pull_request`, sans secret) du job qui commente (avec un jeton minimal), ou exiger une approbation via `environment`. Cas « s1ngularity » sur nx, août 2025.',
  },
  {
    id: 'gha-unpinned', module: 'm14', title: 'Actions non épinglées au SHA',
    status: 'live', kind: 'fix', level: 1, csslp: ['D7', 'D8'], cwe: 'CWE-1357',
    brief: 'Les actions tierces sont référencées par étiquette mobile, que leur mainteneur peut repointer à tout moment.',
    goal: 'Épingler chaque action tierce à un SHA de commit de 40 caractères.',
    file: 'novafact/.github/workflows/ci.yml',
    lessons: ['m14/l02', 'm14/l09'],
    hints: [
      'Une étiquette comme `@v4` est un alias : elle bouge.',
      'Toutes les actions de tous les workflows sont concernées, pas seulement celles de la CI.',
      'Remplace l’étiquette par un SHA de 40 caractères hexadécimaux, avec la version en commentaire.',
    ],
    fix: 'SHA de 40 caractères, Renovate pour les mises à jour, et la politique d’organisation qui l’impose. Cas `tj-actions/changed-files` (CVE-2025-30066, mars 2025).',
  },
  {
    id: 'gha-typosquat-action', module: 'm14', title: 'Action typosquattée',
    status: 'live', kind: 'fix', level: 2, csslp: ['D8'], cwe: 'CWE-1357',
    brief: 'Un workflow référence une action dont le nom de propriétaire est presque celui de l’action officielle.',
    goal: 'Corriger la référence, pour que toutes les actions viennent de propriétaires connus.',
    file: 'novafact/.github/workflows/ci.yml',
    lessons: ['m14/l06', 'm14/l02'],
    hints: [
      'Compare chaque `uses:` à ce que tu écrirais de mémoire.',
      'Une lettre manque quelque part, dans la partie avant le slash.',
      '`action/checkout` n’existe pas — c’est `actions/checkout`.',
    ],
    fix: 'Une lettre manquante suffit : le typosquat vise le pipeline comme il vise npm. Liste blanche d’actions au niveau de l’organisation, épinglage par SHA. `zizmor` : `typosquat-uses`.',
  },
  {
    id: 'gha-artipacked', module: 'm14', title: 'Identifiants git publiés dans un artefact',
    status: 'live', kind: 'fix', level: 2, csslp: ['D7', 'D8'], cwe: 'CWE-522',
    brief: 'Le checkout laisse le jeton dans `.git/config`, et l’étape d’upload téléverse la racine du dépôt.',
    goal: 'Empêcher la persistance des identifiants et restreindre le chemin téléversé.',
    file: 'novafact/.github/workflows/ci.yml',
    lessons: ['m14/l02', 'm14/l03'],
    hints: [
      'Regarde ce que le `path:` de l’artefact englobe exactement.',
      'Le checkout écrit un jeton dans `.git/config` — sauf si on le lui interdit.',
      'Mets `persist-credentials: false` sur le checkout, et un chemin précis sur l’upload.',
    ],
    fix: 'Un artefact est souvent public : tout ce qui y entre est publié. Recherche ArtiPACKED (Unit 42, août 2024), règle `zizmor` `artipacked`.',
  },
  {
    id: 'gha-curl-bash', module: 'm14', title: 'Script tiers exécuté sans vérification',
    status: 'live', kind: 'fix', level: 2, csslp: ['D7', 'D8'], cwe: 'CWE-494',
    brief: 'Une étape de CI télécharge un script et l’exécute directement, sans contrôle d’empreinte.',
    goal: 'Supprimer l’exécution directe d’un script téléchargé à la volée.',
    file: 'novafact/.github/workflows/ci.yml',
    lessons: ['m14/l04', 'm14/l07'],
    hints: [
      'Cherche un tube entre un téléchargement et un interpréteur.',
      'Ce script est une dépendance que personne ne relit ni ne versionne.',
      'Télécharge dans un fichier, vérifie une empreinte versionnée, puis exécute.',
    ],
    fix: 'Un script téléchargé à chaque exécution est une dépendance non versionnée. Empreinte épinglée, ou paquet installé depuis un registre avec lockfile. Compromission du Bash Uploader Codecov (2021).',
  },
  {
    id: 'npm-ci-lockfile', module: 'm14', title: 'npm install en intégration continue',
    status: 'live', kind: 'fix', level: 1, csslp: ['D8'], cwe: 'CWE-1104',
    brief: 'La CI lance une installation qui réécrit le lockfile et autorise des résolutions que personne n’a validées.',
    goal: 'Rendre l’installation reproductible dans tous les workflows.',
    file: 'novafact/.github/workflows/ci.yml',
    lessons: ['m14/l05', 'm13/l06'],
    hints: [
      'Deux commandes npm installent des dépendances. Une seule respecte le lockfile.',
      'L’une peut modifier `package-lock.json` ; l’autre échoue plutôt que de le faire.',
      'Remplace `npm install` par `npm ci`.',
    ],
    fix: '`npm ci` installe exactement le lockfile, ou échoue. Sans cela, la CI et le poste du développeur n’exécutent pas le même code. OpenSSF Scorecard `Pinned-Dependencies`, CICD-SEC-3.',
  },
  {
    id: 'gha-secrets-inherit', module: 'm14', title: 'secrets: inherit vers un workflow réutilisable',
    status: 'live', kind: 'fix', level: 2, csslp: ['D7', 'D8'], cwe: 'CWE-668',
    brief: 'Un job appelle un workflow réutilisable en lui transmettant tous les secrets du dépôt, alors qu’il n’en utilise qu’un.',
    goal: 'Ne transmettre nommément que le secret nécessaire.',
    file: 'novafact/.github/workflows/release.yml',
    lessons: ['m14/l02', 'm14/l08'],
    hints: [
      'Le mot-clé qui transmet tout tient en un mot.',
      'Avec lui, le périmètre des secrets n’est plus lisible dans le fichier appelant.',
      'Remplace `secrets: inherit` par un mapping explicite du seul secret utile.',
    ],
    fix: 'Mapping explicite. `inherit` est commode et c’est exactement son problème. `zizmor` : `secrets-inherit`, `overprovisioned-secrets`. CICD-SEC-6.',
  },
  {
    id: 'gha-cache-poisoning', module: 'm14', title: 'Empoisonnement du cache Actions',
    status: 'live', kind: 'fix', level: 3, csslp: ['D7', 'D8'], cwe: 'CWE-349',
    brief: 'La clé du cache contient une valeur contrôlée par l’auteur d’une PR, et ce cache est restauré par le workflow qui publie le SDK.',
    goal: 'Faire qu’aucun job de publication ne restaure un cache dont la clé dépend d’une entrée contrôlable.',
    file: 'novafact/.github/workflows/release.yml',
    lessons: ['m14/l02', 'm14/l07'],
    hints: [
      'Le cache est un canal d’écriture entre workflows de privilèges différents.',
      'Regarde d’où vient la valeur qui compose la clé.',
      'Compose la clé à partir d’une référence figée, ou retire le cache du job de release.',
    ],
    fix: 'Ce qu’un job faiblement privilégié dépose dans le cache, un job privilégié le restaure et l’exécute. `zizmor` : `cache-poisoning`. Cas Ultralytics, déc. 2024.',
  },
  {
    id: 'npm-provenance', module: 'm14', title: 'Publication sans provenance',
    status: 'live', kind: 'fix', level: 2, csslp: ['D7', 'D8'], cwe: 'CWE-345',
    brief: 'Le job de release publie le SDK avec un jeton de longue durée, sans provenance ni publication de confiance.',
    goal: 'Publier par OIDC avec attestation de provenance, et supprimer le jeton de longue durée.',
    file: 'novafact/.github/workflows/release.yml',
    lessons: ['m14/l09', 'm14/l05'],
    hints: [
      'Trois choses manquent : une permission, un drapeau, et un secret à retirer.',
      'La publication de confiance s’appuie sur un jeton OIDC de courte durée.',
      'Ajoute la permission `id-token: write`, passe `--provenance` à la publication, et retire le jeton.',
    ],
    fix: 'La publication de confiance supprime le secret à voler ; la provenance permet de vérifier d’où vient le paquet et par quel workflow il a été construit.',
  },
  {
    id: 'gha-bot-condition', module: 'm14', title: 'Condition « acteur bot » usurpable',
    status: 'live', kind: 'fix', level: 2, csslp: ['D7', 'D8'], cwe: 'CWE-290',
    brief: 'Une fusion automatique est gardée par une comparaison sur le nom de l’acteur, dans un contexte où cette valeur ne prouve rien.',
    goal: 'Retirer la garde usurpable, ou l’auto-merge qu’elle protège.',
    file: 'novafact/.github/workflows/automerge.yml',
    lessons: ['m14/l02', 'm14/l01'],
    hints: [
      '`github.actor` n’est pas une preuve d’identité dans un contexte `pull_request_target`.',
      'Le contrôle de flux est le premier risque du Top 10 CI/CD.',
      'Supprime la condition sur `github.actor`, et avec elle la fusion automatique.',
    ],
    fix: 'Vérifier le type de l’auteur de la PR et le déclencheur, ou exiger une revue humaine. CICD-SEC-1. `zizmor` : `bot-conditions`.',
  },
  {
    id: 'gha-self-hosted', module: 'm14', title: 'Runner self-hosted ouvert aux forks',
    status: 'live', kind: 'fix', level: 2, csslp: ['D7', 'D8'], cwe: 'CWE-668',
    brief: 'Un workflow déclenché par les pull requests tourne sur un runner self-hosted, sans approbation préalable.',
    goal: 'Empêcher qu’un code de fork s’exécute sur une machine persistante qu’on possède.',
    file: 'novafact/.github/workflows/e2e.yml',
    lessons: ['m14/l02', 'm14/l03'],
    hints: [
      'Un runner self-hosted n’est pas éphémère : ce qu’une PR y laisse, la suivante le trouve.',
      'Deux corrections possibles : changer de runner, ou exiger une approbation.',
      'Passe sur un runner hébergé, ou ajoute un `environment:` soumis à approbation.',
    ],
    fix: 'Runners hébergés pour tout ce qui vient d’un fork, ou approbation obligatoire via `environment`, et runners jetables sinon.',
  },
  {
    id: 'codeowners-ci', module: 'm14', title: 'CODEOWNERS qui ne couvre pas la CI',
    status: 'live', kind: 'fix', level: 1, csslp: ['D7', 'D8'], cwe: 'CWE-1391',
    brief: 'Le fichier protège `src/` mais pas les workflows, ni la configuration npm, ni le lockfile : on peut modifier le pipeline sans revue dédiée.',
    goal: 'Router les chemins sensibles — et seulement eux — vers l’équipe sécurité.',
    file: 'novafact/.github/CODEOWNERS',
    lessons: ['m14/l02', 'm12/l03'],
    hints: [
      'Quatre chemins doivent être couverts : les workflows, CODEOWNERS lui-même, `.npmrc` et le lockfile.',
      'Dans CODEOWNERS, c’est la **dernière** règle qui correspond qui l’emporte : mets les plus précises en bas.',
      'Attention au raccourci qui donne tout le dépôt à la sécurité : il ferait que plus rien n’est relu sérieusement.',
    ],
    fix: 'Le pipeline est du code de production : il mérite la même revue, par les bonnes personnes. CODEOWNERS route aussi vers l’AppSec ce qui touche l’authentification et la crypto. CICD-SEC-1.',
  },
  {
    id: 'npmrc-ignore-scripts', module: 'm14', title: 'Scripts d’installation non neutralisés',
    status: 'live', kind: 'fix', level: 2, csslp: ['D8'], cwe: 'CWE-506',
    brief: 'Rien n’empêche les scripts d’installation des dépendances de s’exécuter, ni sur le poste ni sur le runner.',
    goal: 'Neutraliser par défaut les scripts d’installation.',
    file: 'novafact/.npmrc',
    lessons: ['m14/l03', 'm14/l05'],
    hints: [
      'Une seule ligne de configuration npm suffit.',
      'C’est le vecteur d’exécution des vers qui frappent npm depuis 2025.',
      'Ajoute `ignore-scripts=true` dans `.npmrc`.',
    ],
    fix: '`ignore-scripts=true` (pnpm 10 le fait déjà), plus une allowlist pour les rares paquets à compiler. Vecteur du ver Shai-Hulud comme d’event-stream.',
  },
  {
    id: 'npm-token-in-repo', module: 'm14', title: 'Jeton de publication dans le dépôt',
    status: 'live', kind: 'fix', level: 1, csslp: ['D7', 'D8'], cwe: 'CWE-798',
    brief: 'Un `.npmrc` versionné contient un jeton d’authentification en clair.',
    goal: 'Sortir le jeton du dépôt, en gardant une configuration qui marche en CI.',
    file: 'novafact/.npmrc',
    lessons: ['m14/l05', 'm13/l07'],
    hints: [
      'La ligne fautive commence par `//registry.npmjs.org/`.',
      'Une référence d’environnement est acceptable à cet endroit ; une valeur littérale non.',
      'Remplace la valeur par `${NPM_TOKEN}`, alimenté par un secret de CI.',
    ],
    fix: 'Un secret exposé se **révoque** d’abord : le retirer du fichier ne le retire ni de l’historique ni des clones. Détection en pre-commit et push protection côté forge.',
  },
  {
    id: 'dependency-confusion', module: 'm14', title: 'Confusion de dépendances sur le scope interne',
    status: 'live', kind: 'fix', level: 2, csslp: ['D8'], cwe: 'CWE-427',
    brief: 'Le projet dépend d’un paquet interne sans que son scope soit associé à un registre privé.',
    goal: 'Associer chaque scope interne à son registre.',
    file: 'novafact/.npmrc',
    lessons: ['m14/l05', 'm14/l06'],
    hints: [
      'Regarde les dépendances de `package.json` qui commencent par une arobase.',
      'Le résolveur prend la version la plus haute qu’il trouve, où qu’il la trouve.',
      'Ajoute une ligne `@novafact:registry=…` dans `.npmrc`.',
    ],
    fix: 'Publier une version très haute sur le registre public suffit à détourner l’installation. Scope épinglé au registre privé, et nom de scope réservé publiquement. Alex Birsan (2021).',
  },
  {
    id: 'lockfile-integrity', module: 'm14', title: 'Lockfile détourné',
    status: 'live', kind: 'fix', level: 2, csslp: ['D8'], cwe: 'CWE-494',
    brief: 'Une entrée du lockfile pointe vers un registre tiers et n’a pas d’empreinte d’intégrité.',
    goal: 'Rétablir le registre officiel et une empreinte pour chaque entrée.',
    file: 'novafact/package-lock.json',
    lessons: ['m14/l05', 'm14/l06'],
    hints: [
      'Deux champs disent d’où vient un paquet et ce qu’il contient.',
      'Une entrée sur deux a quelque chose qui cloche.',
      'Remets `resolved` sur le registre officiel et ajoute un champ `integrity`.',
    ],
    fix: 'Un lockfile se relit comme du code : une PR qui modifie `resolved` ou `integrity` sans raison est un signal. Recherche « lockfile injection » (Liran Tal, Snyk, 2022).',
  },
  {
    id: 'npm-pack-leak', module: 'm14', title: 'Fuite de fichiers dans le paquet publié',
    status: 'live', kind: 'fix', level: 1, csslp: ['D8'], cwe: 'CWE-538',
    brief: 'Le `package.json` ne déclare pas ce qui doit être publié : tests, scripts et fichiers de configuration partent dans le tarball.',
    goal: 'Restreindre le contenu publié aux seuls artefacts de distribution.',
    file: 'novafact/package.json',
    lessons: ['m14/l09', 'm14/l05'],
    hints: [
      'Un champ de `package.json` sert de liste blanche pour la publication.',
      'Sans lui, npm publie presque tout ce qui traîne.',
      'Ajoute un champ `files` limité au dossier de distribution.',
    ],
    fix: 'Un champ `files` en liste blanche, et `npm pack --dry-run` lu en revue comme un diff. Ce qui part dans le tarball est public et définitif.',
  },
  {
    id: 'vendor-build-mismatch', module: 'm14', title: 'L’artefact ne correspond pas au source',
    status: 'live', kind: 'fix', level: 3, csslp: ['D8'], cwe: 'CWE-506',
    brief: 'Un paquet vendorisé livre un build « minifié » qui ne correspond pas à ses sources : une ligne s’y est ajoutée.',
    goal: 'Repérer l’écart entre le build livré et les sources, et rétablir un artefact fidèle.',
    file: 'novafact/vendor/novafact-parser/build/index.min.js',
    lessons: ['m14/l07', 'm14/l10'],
    hints: [
      'Compare ce que font les deux fichiers du paquet, pas seulement leur taille.',
      'Le build appelle quelque chose que les sources n’appellent pas.',
      'Une requête réseau et une URL codée en dur n’existent que dans le build : retire-les.',
    ],
    fix: 'C’est la leçon d’xz-utils (CVE-2024-3094) et d’event-stream : le code malveillant était dans le tarball publié, pas dans le dépôt git. Builds reproductibles, attestations de provenance, vérification à l’installation. On ne relit pas ce qu’on n’a pas construit.',
  },
];
